from .utils import get_message, send_message
from .veriables import DEFAULT_PORT, DEFAULT_IP_ADDRESS, MAX_CONNECTIONS, MAX_PACKAGE_LENGTH, ENCODING,\
    ACTION, TIME, USER, ACCOUNT_NAME, PRESENCE, RESPONSE, ERROR
